documents_dir: "data/docs"
eval_questions_dir: "data/eval_questions/"
eval_file_name: "eval_ds.xlsx"

memory:
  directory: "memory/chat_history_{}.csv"
  num_entries: 2

llama_index_cfg:
  basic_rag:
    index_save_dir: "data/indexes/basic_index"
  pagewise_rag:
    index_save_dir: "data/indexes/pagewise_index"
  sentence_retrieval:
    index_save_dir: "data/indexes/sentence_index"
    sentence_window_size: 3
    similarity_top_k: 6
    rerank_top_n: 2
  auto_merging_retrieval:
    index_save_dir: "data/indexes/merging_index"
    chunk_sizes: [2048, 512, 128]
    similarity_top_k: 6 # 12
    rerank_top_n: 2
  llama_eval_method: "auto_merging_retrieval" # sentence_retrieval # auto_merging_retrieval

langchain_cfg:
  splitter_type: recursive # recursive # token
  token_vector_db_save_dir: "data/indexes/langchain_token_index"
  recursive_vector_db_save_dir: "data/indexes/langchain_recursive_index"
  recursive_chunk_size: 1500
  recursive_chunk_overlap: 500
  token_chunk_size: 600
  token_chunk_overlap: 200
  search_type: similarity #similarity # mmr
  k: 6

llm_cfg:
  gpt_model: "gpt-35-turbo-16k"
  # gpt_model: "gpt-4-32k"
  embed_model_name: "text-embedding-ada-002" # "bge-small-en-v1.5"
  rerank_model: "BAAI/bge-reranker-base"
  temperature: 0.0
